create table public.deployment_logs (
  id bigint generated by default as identity primary key,
  deployment_id uuid not null references public.deployments(id) on delete cascade,
  stream text not null check (stream in ('stdout', 'stderr')),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.deployment_logs enable row level security;

create policy "Users can view logs of their own deployments"
on public.deployment_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.deployments
    join public.projects
      on projects.id = deployments.project_id
    where deployments.id = deployment_logs.deployment_id
      and projects.user_id = auth.uid()
  )
);

create index deployment_logs_deployment_id_created_at_idx
on public.deployment_logs (deployment_id, created_at);